__use_yte__: true
__variables__:
  rng: 49274
  remote: "../data/remote"

trainer:
  max_epochs: 2000
  log_every_n_steps: 5
  enable_progress_bar: false
dataloader:
  batch_size: 5

log_wandb: true

tasks:
  # [2025-12-26 Fri] Details on selection in `data_curation.org` and `preprocessing.org`
  classification:
    [
      "gentamicin_class",
      "tetracycline_class",
      "trimethoprim-sulfamethoxazole_class",
      "ciprofloxacin_class",
      "cefoxitin_class",
    ]
  regression:
    [
      "gentamicin",
      "tetracycline",
      "trimethoprim-sulfamethoxazole",
      "ciprofloxacin",
      "cefoxitin",
    ]

# * Embedding comparison

compare_embeddings:
  bootstrap_rounds: 5
  seq_count: 25 # [2026-03-26 Thu] this actually completes
  # seq_prop: 0.01
  n_samples_per: null
  methods:
    - neighbor_proportion
    - pair_distance_distribution
    - clustering
  pair_distance_distribution:
    cols: ["sample", "gene", "hamr_drug_class"]
    distance_metric: cosine
    kws:
      n_pairs_per: 25
  neighbor_proportion:
    cols: ["sample", "gene", "hamr_drug_class"]
    kws:
      metric: "cosine"
      n_neighbors: 8
  cluster_on:
    - "sample" # do the sequence embeddings recover their original genomes when clustered?
    - "gene" # do sequence embeddings cluster by genes?
    - "hamr_drug_class"

compare_pooled:
  bootstrap_rounds: 3
  n_samples_per: null
  methods:
    - neighbor_proportion
    - covariate_distance_correlation
    - pair_distance_distribution
    - clustering
  pair_distance_distribution:
    cols: ["genus", "family", "isolation_source_broad"]
    distance_metric: cosine
    kws:
      n_pairs_per: 20
  covariate_distance_correlation:
    cols:
      - "gentamicin"
      - "tetracycline"
      - "trimethoprim-sulfamethoxazole"
      - "ciprofloxacin"
      - "cefoxitin"
    distance_metric: "cosine"
  neighbor_proportion:
    cols: ["genus", "family", "isolation_source_broad"]
    kws:
      metric: "cosine"
      n_neighbors: 8
      null_bootstrap_rounds: 1000
      include_null: true
      include_impurity: true
  cluster_on:
    - "genus"
    - "family"
    - "isolation_source_broad"
  continuous:
    - "gentamicin"
    - "tetracycline"
    - "trimethoprim-sulfamethoxazole"
    - "ciprofloxacin"
    - "cefoxitin"

# * Metadata

seq_metadata:
  hamronization: ?f"{remote}/output/ast_browser/funcscan/all/hamronization_combined_report.tsv"
  combgc: ?f"{remote}/output/ast_browser/funcscan/all/combgc"
  bakta: ?f"{remote}/output/ast_browser/funcscan/all/bakta"
  ampcombi: ?f"{remote}/output/ast_browser/funcscan/all/Ampcombi_summary_cluster.tsv"

genomes: ?f"{remote}/genomes/ast_browser_batches/all"

# * Evaluation

# ** Holdout

holdout:
  __variables__:
    name2size: { very_few_shot: 0.15, mid: 0.5, few_shot: 0.3, standard: 0.8 }
  models: [baseline, mlp_basic, mlp_deep]
  bootstrap_splits:
    ?for name, train_size in name2size.items():
      ?name:
        repeat: 5
        kws:
          train_size: ?train_size
          shuffle: true
  validation_kws:
    test_size: 0.2
  splits:
    # Naming convention is to describe the training set:
    # - "no" indicates absence from training set e.g. no_esch means no Escherichia in the training set
    # - "only" indicates only that group in the training set
    taxonomy_no_esch:
      genus:
        Escherichia: EXACT
    taxonomy_no_rare:
      species_representation:
        intermediate: EXACT
        minority: EXACT
    taxonomy_no_salmonella:
      genus:
        Salmonella: EXACT
    project_no_narms:
      umbrella_project:
        NARMS: EXACT
    project_only_narms:
      umbrella_project:
        NARMS: NOT
    environment_no_animals:
      isolation_source_broad:
        animal: EXACT
        animal_product: EXACT
    environment_no_tissue:
      isolation_source_broad:
        tissue/organ: EXACT
        skin/soft_tissue: EXACT
        urogenital: EXACT
        joint/orthopedic: EXACT
    interest_group_none:
      interest_group:
        WHO_critical: EXACT
        WHO_high: EXACT
        WHO_medium: EXACT
    year_before_2019:
      collection_year:
        "2019": GT
# ** CV

cross_validate:
  models:
    - baseline
    - mlp_basic
    - mlp_deep
  validation_kws:
    test_size: 0.2
  k_fold:
    n_repeats: 2
    n_splits: 5
  control_tasks: # Mappings of target tasks to random control tasks
    ?for cls in this['tasks']["classification"]:
      ?cls: genus

# * Data prep

pool_embeddings:
  methods:
    mean:
    sum:
    max:
    similarity:
    random:
      rng: ?rng
    amr_mechanisms:
      method: seq_subset
      priority:
        [
          "antibiotic inactivation",
          "antibiotic target alteration",
          "antibiotic efflux",
        ]
      subset_col: hamr_resistance_mechanism
      agg: null
      split: ";"
preprocessing: # NOTE: must prefix baseline pooling methods with "baseline-"
  baseline-kmer5:
    method: kmer
    k: 5
  baseline-kmer9:
    method: kmer
    k: 9
  # [2026-02-28 Sat] Generated the below already
  # TODO: [2026-02-28 Sat] rename your previous run of kmer10 to kmer7...
  # baseline-kmer10:
  #   method: kmer
  #   k: 7
  baseline-feature_presence_bakta:
    source: "bakta"
    method: feature_presence
    feature_whitelist: "../data/meta/bakta_frequent_features_5000.txt"
    #   # [2026-02-24 Tue] Top 5000 most frequent features in combined Bakta output
    # TODO: check if recoding the features works
  baseline-feature_presence_bakta_clusters:
    source: "bakta"
    method: feature_presence
    feature_whitelist: "../data/meta/frequent_clusters_5000.txt"
    recoding_join_cols: [Gene, Product]
    recode_file: ?f"{remote}/bakta_mmseqs_2026-03-25/cluster_recode_aa.csv"
    # TODO: check if recoding the features works
  # baseline-feature_presence_hamr:
  #   source: "hamr"
  #   method: feature_presence
  #   # id_regexp: "([^.]*)"
  bin:
    split_method: bin
  orf_only:
    split_method: bakta
  orf_w_downstream:
    split_method: bakta
    utr_amount: [0, 200]
  orf_w_upstream:
    split_method: bakta
    utr_amount: [200, 0]
  orf_w_both:
    split_method: bakta
    utr_amount: [200, 200]
