__use_yte__: true
__variables__:
  rng: 49274
pool_embeddings:
  methods:
    mean:
    sum:
    max:
    similarity:
    random:
      rng: ?rng
    amr_mechanisms:
      method: seq_subset
      priority:
        [
          "antibiotic inactivation",
          "antibiotic target alteration",
          "antibiotic efflux",
        ]
      subset_col: hamr_resistance_mechanism
      agg: null
      split: ";"

tasks:
  # [2025-12-26 Fri] Details on selection in `data_curation.org` and `preprocessing.org`
  classification:
    [
      "gentamicin_class",
      "tetracycline_class",
      "trimethoprim-sulfamethoxazole_class",
      "ciprofloxacin_class",
      "cefoxitin_class",
    ]
  regression:
    [
      "gentamicin",
      "tetracycline",
      "trimethoprim-sulfamethoxazole",
      "ciprofloxacin",
      "cefoxitin",
    ]

compare_embeddings:
  bootstrap_rounds: 5
  n_samples_per: 150
  methods:
    - neighbor_proportion
    - pair_distance_distribution
    - clustering
  pair_distance_distribution:
    cols: ["sample", "bakta_gene", "hamr_drug_class"]
    distance_metric: cosine
    kws:
      n_pairs_per: 25
  neighbor_proportion:
    cols: ["sample", "bakta_gene", "hamr_drug_class"]
    kws:
      metric: "cosine"
      n_neighbors: 8
  cluster_on:
    - "sample" # do the sequence embeddings recover their original genomes when clustered?
    - "bakta_gene" # do sequence embeddings cluster by genes?
    - "hamr_drug_class"

compare_pooled:
  bootstrap_rounds: 3
  n_samples_per: null
  methods:
    - neighbor_proportion
    - covariate_distance_correlation
    - pair_distance_distribution
    - clustering
  pair_distance_distribution:
    cols: ["genus", "family", "isolation_source_broad"]
    distance_metric: cosine
    kws:
      n_pairs_per: 20
  covariate_distance_correlation:
    cols:
      - "gentamicin"
      - "tetracycline"
      - "trimethoprim-sulfamethoxazole"
      - "ciprofloxacin"
      - "cefoxitin"
    distance_metric: "cosine"
  neighbor_proportion:
    cols: ["genus", "family", "isolation_source_broad"]
    kws:
      metric: "cosine"
      n_neighbors: 8
      null_bootstrap_rounds: 1000
      include_null: true
      include_impurity: true
  cluster_on:
    - "genus"
    - "family"
    - "isolation_source_broad"
  continuous:
    - "gentamicin"
    - "tetracycline"
    - "trimethoprim-sulfamethoxazole"
    - "ciprofloxacin"
    - "cefoxitin"

seq_metadata:
  hamronization: "../data/remote/output/ast_browser/funcscan/all/hamronization_combined_report.tsv"
  combgc: "../data/remote/output/ast_browser/funcscan/all/combgc"
  bakta: "../data/remote/output/ast_browser/funcscan/all/bakta"
  ampcombi: "../data/remote/output/ast_browser/funcscan/all/Ampcombi_summary_cluster.tsv"

genomes: "../data/remote/genomes/ast_browser_batches/all"
