seq_metadata:
  hamronization: "../data/remote/output/ast_browser/funcscan/batch4/reports/hamronization_summarize/hamronization_combined_report.tsv"
  combgc: "../data/remote/output/ast_browser/funcscan/batch4/reports/combgc"
  bakta: "../data/remote/output/ast_browser/funcscan/batch4/annotation/bakta/all"
  ampcombi: "../data/remote/output/ast_browser/funcscan/batch4/reports/ampcombi2/Ampcombi_summary_cluster.tsv"
genomes: "../data/remote/genomes/ast_browser_batches/4"
