seq_metadata:
  hamronization: "../data/remote/output/ast_browser/funcscan/batch6/reports/hamronization_summarize/hamronization_combined_report.tsv"
  combgc: "../data/remote/output/ast_browser/funcscan/batch6/reports/combgc"
  bakta: "../data/remote/output/ast_browser/funcscan/batch6/annotation/bakta/all"
  ampcombi: "../data/remote/output/ast_browser/funcscan/batch6/reports/ampcombi2/Ampcombi_summary.tsv"
genomes: "../data/remote/genomes/ast_browser_batches/6_bacass"
