[vars]
smk_test_args = "test=True log_wandb=False"

[env]
SMK_EXECUTOR = "slurm"
SMK_PROFILE = "profiles/test"

[tasks.report]
dir = "./snakemake"
usage = '''
flag "-e --test" help="Test run" default=#false
flag "-d --date [date]" help="Date of run" default="no_date"
flag "-i --in_date [date]" help="Input run date" default="no_date"
flag "-c --clear" help="Delete all output before running" default=#false
'''
run = '''
report="../docs/reports/${usage_date}.zip"
conf=""
if [[ "${usage_test}" == "true" ]]; then
   conf={{vars.smk_test_args}}
fi
args="--profile profiles/local --executor local"
if [[ "${usage_clear}" == "true" ]]; then
   snakemake -s report.smk --config ${conf} \
          in_date=${usage_in_date} \
          date=${usage_date} \
          --delete-all-output ${args}
fi
snakemake -s report.smk --config ${conf} \
          in_date=${usage_in_date} \
          date=${usage_date} \
          --report-after-run --report ${report} ${args}
unzip -q -o "${report}" -d ../docs/reports
'''

[tasks.smk_test]
dir = "./snakemake"
# TODO: make note that whatever is in the <> or [] are just to show the help information
# for flags. For args, it is the usage parameter name
usage = '''
arg "<file>" default="evaluate.smk" help="snakefile to run"
flag "-l --local" help="Run locally" default=#false
flag "-d --date [date]" help="Date of run" default="no_date"
flag "-i --in_date [date]" help="Input run date" default="esm_test"
'''
run = '''
if [[ "${usage_local?}" == "true" ]]; then
   export SMK_EXECUTOR=local
   export SMK_PROFILE=profiles/local
fi
snakemake -s ${usage_file} --config {{vars.smk_test_args}} \
          in_date=${usage_in_date} embedding=esm \
          date=${usage_date} \
          --profile "${SMK_PROFILE}" \
          --executor "${SMK_EXECUTOR}" 
'''


# * Nextflow runs
[tasks.bacass]
# TODO: [2026-01-13 Tue] Not yet completed
dir = "/data/project/stemcell/shannc/repos/amr_predict/pipelines"
run = '''
nextflow run -r master nf-core/bacass \
    -resume \
    --input ~/amr_predict/config/nf_runs/ast_browser_samplesheet_2025-12-05.csv \
    --kraken2db "/data/project/stemcell/shannc/repos/amr_predict/cache/k2_standard_16_GB_20250714.tar.gz" \
    --kmerfinderdb "/data/project/stemcell/shannc/repos/amr_predict/cache/20190108_kmerfinder_stable_dirs.tar.gz" \
    --outdir "${remote}/output/ast_browser/bacass_2025-12-05" \
    -profile singularity \
    --skip_annotation \
    --skip_kmerfinder \
    --assembly_type "short" \
    -c "./nf_config_fix.config"
'''

[tasks.ast_funcscan]
# NOTE: batch 4 on [2026-01-08 Thu]
dir = "/data/project/stemcell/shannc/repos/amr_predict/pipelines"
usage = '''
arg "[batch]" help="Choice of batch" {
    choices "1" "2" "3" "4" "5"
    default "4"
}
'''
run = '''
remote=".."
nextflow run nf-core/funcscan \
    --input ~/amr_predict/config/nf_runs/funcscan/ast_browser_d-${usage_batch}_2025-12-04.csv \
    --outdir "${remote}/output/ast_browser/funcscan/batch${usage_batch}" \
    -profile singularity \
    --run_arg_screening \
    --run_amp_screening \
    --run_bgc_screening \
    --annotation_tool bakta \
    --annotation_bakta_db "${remote}/datasets/bakta_db_v5.1_full" \
    --save_annotations true
'''
