[vars]
smk_test_args = "test=True log_wandb=False"

[env]
SMK_EXECUTOR = "slurm"
SMK_PROFILE = "profiles/test"

[tasks]
send = "rsync ./mise.toml $stem_ip:~/amr_predict"

[tasks.send_gen_scripts]
dir = "snakemake/gen_bias/scripts"
usage = '''
arg "<file>" help="File to send"
'''
run = '''
rsync "${usage_file}" $stem_ip:~/amr_predict/snakemake/gen_bias/scripts
'''

[tasks.send_gen]
dir = "snakemake/gen_bias"
usage = '''
arg "<file>" default="" help="File to send"
'''
run = '''
if [[ -z "${usage_file}" ]]; then
    rsync env.py $stem_ip:~/amr_predict/snakemake/gen_bias
    rsync env.yaml $stem_ip:~/amr_predict/snakemake/gen_bias
    rsync test_env.yaml $stem_ip:~/amr_predict/snakemake/gen_bias
    rsync Snakefile $stem_ip:~/amr_predict/snakemake/gen_bias
    rsync main.py $stem_ip:~/amr_predict/snakemake/gen_bias
    rsync test.sh $stem_ip:~/amr_predict/snakemake/gen_bias
    rsync run.sh $stem_ip:~/amr_predict/snakemake/gen_bias
else
    rsync "${usage_file}" $stem_ip:~/amr_predict/snakemake/gen_bias
fi
'''


[tasks.report]
dir = "./snakemake"
usage = '''
flag "-e --test" help="Test run" default=#false
flag "-d --date [date]" help="Date of run" default="no_date"
flag "-i --in_date [date]" help="Input run date" default="no_date"
flag "-c --clear" help="Delete all output before running" default=#false
'''
run = '''
report="../docs/reports/${usage_date}.zip"
conf=""
if [[ "${usage_test}" == "true" ]]; then
   conf={{vars.smk_test_args}}
fi
args="--profile profiles/local --executor local"
if [[ "${usage_clear}" == "true" ]]; then
   snakemake -s report.smk --config ${conf} \
          in_date=${usage_in_date} \
          date=${usage_date} \
          --delete-all-output ${args}
fi
snakemake -s report.smk --config ${conf} \
          in_date=${usage_in_date} \
          date=${usage_date} \
          --report-after-run --report ${report} ${args}
unzip -q -o "${report}" -d ../docs/reports
'''

[tasks.print]
run = '''
srun --qos=cpu24h --mem=5G echo "slurm test"
'''

[tasks.smk_test]
dir = "./snakemake"
# TODO: make note that whatever is in the <> or [] are just to show the help information
# for flags. For args, it is the usage parameter name
usage = '''
arg "<file>" default="evaluate.smk" help="snakefile to run"
flag "-l --local" help="Run locally" default=#false
flag "-d --date [date]" help="Date of run" default="no_date"
flag "-i --in_date [date]" help="Input run date" default="esm_test"
'''
run = '''
if [[ "${usage_local?}" == "true" ]]; then
   export SMK_EXECUTOR=local
   export SMK_PROFILE=profiles/local
fi
snakemake -s ${usage_file} --config {{vars.smk_test_args}} \
          in_date=${usage_in_date} embedding=esm \
          date=${usage_date} \
          --profile "${SMK_PROFILE}" \
          --executor "${SMK_EXECUTOR}"
'''

# * Generation bias

[tasks.apptainer_build_gen]
env = { APPTAINER_TMPDIR = "/home/shannc/.cache/apptainer_builds" }
dir = "./snakemake/gen_bias"
run = '''
outdir=../../data/remote/images
if [[ ! -e "${outdir}" ]]; then
   echo "Directory not mounted!"
   exit
fi
build_if_not_exists () {
    if [[ ! -e "${outdir}/${1}.sif" ]]; then 
       apptainer build "${1}.sif" builds/"${1}".def
       mv "${1}.sif" "${outdir}/${1}.sif"
    fi                    
}

build_if_not_exists evo_design
build_if_not_exists meme
build_if_not_exists parasail
build_if_not_exists evo
build_if_not_exists ntv3
build_if_not_exists genome_ocean
'''

[tasks.gen_run]
dir = "./snakemake/gen_bias"
run = '''
snakemake --use-singularity \
	--singularity-args "--nv --bind ../../src:/py_lib --bind /data/project:/data/project --cleanenv" \
	--configfile all_models.yaml \
	"$@"
'''

[tasks.gen_test]
dir = "./snakemake/gen_bias"
run = '''
snakemake --use-singularity \
	--singularity-args "--nv --bind ../../src:/py_lib --bind /data/project:/data/project --cleanenv" \
	--configfile test_env.yaml --profile profiles/test/config.yaml \
	"$@"
'''

[tasks.prepare_placement]
# Prepare reference tree from FASTA file to use
dir = "./data/temp"
usage = '''
arg "<accession>" default="" help="Gene accession to download"
arg "<name>" default="" help="Name of output"
'''
run = '''
outdir=../remote/placements
if [[ ! -e "${outdir}" ]]; then
   echo "Directory not mounted!"
   exit
fi
dir="${outdir}/datasets/${usage_accession}"
file="${dir}/data/rna.fna"
if [[ ! -e ${dir} ]]; then
   datasets download gene accession ${usage_accession} --ortholog all

   unzip -o ncbi_dataset.zip
   mv ncbi_dataset "${dir}" 
   rm -Rf ncbi_dataset.zip
fi

tree="${outdir}/${usage_name}.nwk"
aligned="${outdir}/${usage_name}_aligned.fasta"
if [[ ! -e "${outdir}" ]]; then
   echo "Directory not mounted!"
   exit
fi
srun --qos=cpu24h --mem=30G famsa "${file}" "${aligned}"
srun --qos=cpu24h --mem=30G dipper_cpu -i m -I "${aligned}" -O "${tree}" 
'''

[tasks.apptainer_build]
env = { APPTAINER_TMPDIR = "/home/shannc/Bio_SDD/build" }
run = '''
apptainer build image_new.sif build_editable.def
'''
