from pathlib import Path
import time
from env import SnakeEnv
import os


configfile: "env.yaml"


"""
Output is structured as

<outdir>/
├── generated/
│   └── <model_name>/
│       └── <prefix_name>.fasta
├── prefix_comparison.csv
├── perturbation_sensitivity.csv
├── motifs_domains.csv
└── physicochemical.csv
"""

ENV = SnakeEnv.new(config)
OUTDIR = ENV.outdir
OUTPUTS = ENV.get_outputs()
os.environ["HF_HOME"] = ENV.huggingface


rule all:
    input:
        *OUTPUTS["generated"],
        *OUTPUTS["motifs"],
        *OUTPUTS["taxonomy"],
        # *OUTPUTS["metrics"], # TODO: uncomment after finishing


rule generate:
    output:
        f"{OUTDIR}/generated/{{model}}/{{prefix}}.fasta",
    params:
        script=lambda wc: ENV.model_script(wc.get("model")),
        prefix_fasta=lambda wc: ENV.get_prefix_file(wc["prefix"]),
        kws=lambda wc: ENV.model_kws(wc.get("model")),
        n=lambda wc: ENV.prefix2data[wc.get("prefix")].get("n", ENV.n) or ENV.n,
        hf=ENV.huggingface,
    resources:
        **ENV.resources["gpu40"],
    singularity:
        lambda wc: ENV.model_image(wc["model"])
    shell:
        """
        export HF_HOME='{params.hf}'
        python {params.script} {params.kws} \
                --prompt {params.prefix_fasta} \
                --output {output[0]} \
                --num {params.n}
        """


rule similarity_stats:
    input:
        f"{OUTDIR}/generated/{{model}}/{{prefix}}.fasta",
    singularity:
        ENV.singularity.get("similarity_stats")
    params:
        prefix_fasta=lambda wc: ENV.get_prefix_file(wc["prefix"], full=True),
        funcname=config.get("parasail", "sw_stats_striped_16"),
    output:
        temp(f"{OUTDIR}/similarity_raw/{{model}}/{{prefix}}.tmp.csv"),
    shell:
        """
        parasail_aligner -d \
                -q {params.prefix_fasta} \
                -f {input[0]} \
                -a {params.funcname} \
                -g {output[0]}
        """


rule fmt_similarity_stats:
    input:
        generated=f"{OUTDIR}/generated/{{model}}/{{prefix}}.fasta",
        tmp=f"{OUTDIR}/similarity_raw/{{model}}/{{prefix}}.tmp.csv",
    singularity:
        ENV.singularity.get("fmt_similarity_stats")
    params:
        cols=",".join(
            [
                "query",
                "index",
                "length1",
                "length2",
                "score",
                "end_query",
                "end_ref",
                "n_matches",
                "similarities",
                "length",
            ]
        ),
    output:
        seqnames=temp(f"{OUTDIR}/similarity_raw/{{model}}/{{prefix}}.seqnames.csv"),
        raw=f"{OUTDIR}/similarity_raw/{{model}}/{{prefix}}.csv",
    shell:
        """
        grep '>' {input.generated} | sed 's/^>//' | xan -n rename id | \
                xan enum > {output.seqnames}

        xan rename -n {params.cols} {input.tmp} | \
                xan join index {output.seqnames} - | \
                xan drop index > {output.raw}
         """


rule describe_protein_seqs:
    input:
        f"{OUTDIR}/generated/{{model}}/{{prefix}}.fasta",
    params:
        prefix_fasta=lambda wc: ENV.get_prefix_file(wc["prefix"], full=True),
    output:
        mean=f"{OUTDIR}/protein_descriptor_means/{{model}}/{{prefix}}.csv",
        vals=f"{OUTDIR}/protein_descriptor_raw/{{model}}/{{prefix}}.csv",


# rule compare_protein_descriptors:
# TODO: after getting the values from rule above, compare them
# across prefix groups


rule find_motifs:
    input:
        f"{OUTDIR}/generated/{{model}}/{{prefix}}.fasta",
    singularity:
        ENV.singularity.get("find_motifs")
    output:
        tsv=f"{OUTDIR}/motifs/{{model}}/{{prefix}}.tsv",
    params:
        prefix_fasta=lambda wc: ENV.get_prefix_file(wc["prefix"], full=True),
        thresh=ENV.fimo.thresh,
        motifs=lambda wc: ENV.get_motif_file(wc["prefix"]),
    shell:
        """
        fimo --thresh {params.thresh} \
             --skip-matched-sequence \
             {params.motifs} {params.prefix_fasta} > {output[0]}
        fimo --thresh {params.thresh} \
             --skip-matched-sequence \
             {params.motifs} {input[0]} >> {output[0]}        
        """


rule classify_taxonomy:
    input:
        f"{OUTDIR}/generated/{{model}}/{{prefix}}.fasta",
    params:
        db=ENV.taxdb,
        prefix_fasta=lambda wc: ENV.get_prefix_file(wc["prefix"], full=True),
    threads: 4
    singularity:
        ENV.singularity.get("classify_taxonomy")
    output:
        f"{OUTDIR}/taxonomy/{{model}}/.{{prefix}}/mmseqs_tophit_aln",
        f"{OUTDIR}/taxonomy/{{model}}/.{{prefix}}/mmseqs_report",
        f"{OUTDIR}/taxonomy/{{model}}/.{{prefix}}/mmseqs_lca.tsv",
        f"{OUTDIR}/taxonomy/{{model}}/.{{prefix}}/mmseqs_tophit_report",
    shell:
        f"""
        mmseqs easy-taxonomy {{input[0]}} {{params.prefix_fasta}} \
                {{params.db}} \
                {OUTDIR}/taxonomy/{{wildcards.model}}/.{{wildcards.prefix}}/mmseqs \
                {OUTDIR}/taxonomy/{{wildcards.model}}/.{{wildcards.prefix}}_tmp \
                --tax-lineage 1 \
                --format-mode 4 \
                --search-type 3
        """


rule sort_taxonomy_hits:
    input:
        f"{OUTDIR}/taxonomy/{{model}}/.{{prefix}}/mmseqs_tophit_aln",
    output:
        f"{OUTDIR}/taxonomy/{{model}}/{{prefix}}.csv",
    run:
        import polars as pl

        # Sort by evalue then bitscore ranking i.e. pick sequences with the lowest evalue,
        # (likely to have multiple sequences with the same evalue)
        # then get the best hit by bitscore
        df = pl.read_csv(input[0], separator="\t").with_columns(
            rank=pl.col("evalue").rank().over("query")
        )
        best_evalue = df.group_by("query").agg(min_rank=pl.col("rank").min())
        df = (
            df.join(best_evalue, on="query")
            .filter(pl.col("rank") == pl.col("min_rank"))
            .drop(["rank", "min_rank"])
        )
        df = (
            df.group_by("query")
            .agg(pl.all().top_k_by(k=1, by="bits"))
            .explode(pl.all().exclude("query"))
        )
        df.write_csv(output[0])
