from pathlib import Path
import time
from env import SnakeEnv
import os


configfile: "env.yaml"


"""
Output is structured as

<outdir>/
├── generated/
│   └── <model_name>/
│       └── <prompt_name>.fasta
├── prompt_comparison.csv
├── perturbation_sensitivity.csv
├── motifs_domains.csv
└── physicochemical.csv
"""

ENV = SnakeEnv.new(config)
OUTDIR = ENV.outdir
OUTPUTS = ENV.get_outputs()
PROMPTS = OUTDIR / ".prompts"
INDICES = OUTDIR / ".indices"
PROMPTS_FULL = OUTDIR / ".prompts_full"

os.environ["HF_HOME"] = ENV.huggingface

CUDA_VISIBLE_DEVICES = os.environ.get("CUDA_VISIBLE_DEVICES", 0)
# Pass the correct visible devices into the container
# Is an issue when using the `--cleanenv` flag


rule all:
    input:
        *OUTPUTS["generated"],
        *OUTPUTS["motifs"],
        *OUTPUTS["taxonomy"],
        *OUTPUTS["nuc_similarity"],
        *OUTPUTS["aa_similarity"],
        *OUTPUTS["protein_descriptors"],


rule fmt_prompts:
    output:
        # Would have liked to make these temporary, if not for the fact
        # it would cause the workflow to re-run the `generate` rule
        prompt=f"{PROMPTS}/{{prompt}}.fasta",
        full_trimmed=f"{PROMPTS_FULL}_trimmed/{{prompt}}.fasta",
        full=f"{PROMPTS_FULL}/{{prompt}}.fasta",
        aa=f"{PROMPTS_FULL}_aa/{{prompt}}.fasta",
        aa_trimmed=f"{PROMPTS_FULL}_aa_trimmed/{{prompt}}.fasta",
        # `_trimmed` is the original prompt sequence without the
        # upstream component used for the prompt
        # for aa, trimming occurs prior to translation
    params:
        prompt2data=ENV.prompt2data,
    script:
        "main.py"


rule generate:
    output:
        f"{OUTDIR}/generated/{{model}}/{{prompt}}.fasta",
    input:
        f"{PROMPTS}/{{prompt}}.fasta",
    params:
        script=lambda wc: ENV.model_script(wc.get("model")),
        kws=lambda wc: ENV.model_kws(wc.get("model")),
        n=lambda wc: ENV.prompt2data[wc.get("prompt")].get("n", ENV.n) or ENV.n,
        hf=ENV.huggingface,
        cvd=CUDA_VISIBLE_DEVICES,
    resources:
        **ENV.resources["gpu40"],
    singularity:
        lambda wc: ENV.model_image(wc["model"])
    shell:
        """
        export HF_HOME='{params.hf}'
        export CUDA_VISIBLE_DEVICES={params.cvd}
        python {params.script} {params.kws} \
                --prompt {input[0]} \
                --output {output[0]} \
                --prefix "{wildcards.model}|" \
                --prepend_prompt_to_output False \
                --num {params.n}
        """


rule gen_index:
    input:
        f"{OUTDIR}/generated/{{model}}/{{prompt}}.fasta",
    output:
        f"{INDICES}/{{model}}/{{prompt}}",
    shell:
        """
        grep '>' {input[0]} | sed 's/^>//' | xan -n rename id | \
                xan enum > {output[0]}
        """


rule translate_fasta:
    input:
        f"{OUTDIR}/generated/{{model}}/{{prompt}}.fasta",
    output:
        f"{OUTDIR}/generated_aa/{{model}}/{{prompt}}.fasta",
    script:
        "main.py"


rule describe_protein_seqs:
    input:
        prompt_full=f"{PROMPTS_FULL}_aa_trimmed/{{prompt}}.fasta",
        generated=f"{OUTDIR}/generated_aa/{{model}}/{{prompt}}.fasta",
    output:
        mean=f"{OUTDIR}/protein_descriptors/{{model}}/{{prompt}}-means.csv",
        # For each descriptor, the mean difference of the generated sequence from the
        # prompt
        vals=f"{OUTDIR}/protein_descriptors/{{model}}/{{prompt}}-raw.csv",
    script:
        "main.py"


# rule compare_protein_descriptors:
# TODO: after getting the values from rule above, compare them
# across prompt groups


rule find_motifs:
    input:
        generated=f"{OUTDIR}/generated/{{model}}/{{prompt}}.fasta",
        prompt=f"{PROMPTS}/{{prompt}}.fasta",
        prompt_full=f"{PROMPTS_FULL}/{{prompt}}.fasta",
    singularity:
        ENV.singularity.get("find_motifs")
    output:
        tsv=f"{OUTDIR}/motifs/{{model}}/{{prompt}}.tsv",
        tmp=temp(f"{OUTDIR}/motifs/{{model}}/{{prompt}}.fasta"),
    params:
        thresh=ENV.fimo.thresh,
        motifs=lambda wc: ENV.get_motif_file(wc["prompt"]),
    shell:
        """
        fimo --thresh {params.thresh} \
             --skip-matched-sequence \
             {params.motifs} {input.prompt_full} > {output[0]}
        fimo --thresh {params.thresh} \
             --skip-matched-sequence \
             {params.motifs} {input.generated} >> {output[0]}        
        """


rule classify_taxonomy:
    input:
        generated=f"{OUTDIR}/generated/{{model}}/{{prompt}}.fasta",
        prompt_full=f"{PROMPTS_FULL}/{{prompt}}.fasta",
    params:
        db=ENV.taxdb,
    threads: 4
    singularity:
        ENV.singularity.get("classify_taxonomy")
    output:
        f"{OUTDIR}/taxonomy/{{model}}/.{{prompt}}/mmseqs_tophit_aln",
        f"{OUTDIR}/taxonomy/{{model}}/.{{prompt}}/mmseqs_report",
        f"{OUTDIR}/taxonomy/{{model}}/.{{prompt}}/mmseqs_lca.tsv",
        f"{OUTDIR}/taxonomy/{{model}}/.{{prompt}}/mmseqs_tophit_report",
    shell:
        f"""
        mmseqs easy-taxonomy {{input.generated}} {{input.prompt_full}} \
                {{params.db}} \
                {OUTDIR}/taxonomy/{{wildcards.model}}/.{{wildcards.prompt}}/mmseqs \
                {OUTDIR}/taxonomy/{{wildcards.model}}/.{{wildcards.prompt}}_tmp \
                --tax-lineage 1 \
                --format-mode 4 \
                --search-type 3
        """


rule sort_taxonomy_hits:
    input:
        f"{OUTDIR}/taxonomy/{{model}}/.{{prompt}}/mmseqs_tophit_aln",
    output:
        f"{OUTDIR}/taxonomy/{{model}}/{{prompt}}.csv",
    run:
        import polars as pl

        # Sort by evalue then bitscore ranking i.e. pick sequences with the lowest evalue,
        # (likely to have multiple sequences with the same evalue)
        # then get the best hit by bitscore
        df = pl.read_csv(input[0], separator="\t").with_columns(
            rank=pl.col("evalue").rank().over("query")
        )
        best_evalue = df.group_by("query").agg(min_rank=pl.col("rank").min())
        df = (
            df.join(best_evalue, on="query")
            .filter(pl.col("rank") == pl.col("min_rank"))
            .drop(["rank", "min_rank"])
        )
        df = (
            df.group_by("query")
            .agg(pl.all().top_k_by(k=1, by="bits"))
            .explode(pl.all().exclude("query"))
        )
        df.write_csv(output[0])


# * Sequence similarity


rule similarity:
    input:
        generated=f"{OUTDIR}/generated/{{model}}/{{prompt}}.fasta",
        prompt_full=f"{PROMPTS_FULL}_trimmed/{{prompt}}.fasta",
    params:
        kws="",
    output:
        "PLACEHOLDER",
    shell:
        f"""
        parasail_aligner -x \
                -a {ENV.parasail.fn} \
                -e {ENV.parasail.gap_extend} \
                -o {ENV.parasail.gap_open} \
                -m {ENV.parasail.matrix} \
                -M {ENV.parasail.match} \
                -X {ENV.parasail.mismatch} \
                {{params.kws}} -g {{output[0]}}
        """
        # Require -x flag to ensure that no sequence pair is omitted from comparison


use rule similarity as similarity_to_prompt with:
    params:
        kws=lambda _, input: " ".join(
            ["-d", "-q", input.prompt_full, "-f", input.generated]
        ),
    singularity:
        ENV.singularity.get("similarity")
    output:
        temp(f"{OUTDIR}/.similarity_tmp_nuc/{{model}}/{{prompt}}-to_prompt.csv"),


use rule similarity as similarity_self with:
    params:
        kws=lambda _, input: " ".join(["-d", "-f", input.generated]),
    singularity:
        ENV.singularity.get("similarity")
    output:
        temp(f"{OUTDIR}/.similarity_tmp_nuc/{{model}}/{{prompt}}-self.csv"),


use rule similarity as aa_similarity_to_prompt with:
    input:
        generated=f"{OUTDIR}/generated_aa/{{model}}/{{prompt}}.fasta",
        prompt_full=f"{PROMPTS_FULL}_aa/{{prompt}}.fasta",
    params:
        kws=lambda _, input: " ".join(["-q", input.prompt_full, "-f", input.generated]),
    singularity:
        ENV.singularity.get("similarity")
    output:
        temp(f"{OUTDIR}/.similarity_tmp_aa/{{model}}/{{prompt}}-to_prompt.csv"),


use rule similarity as aa_similarity_self with:
    input:
        generated=f"{OUTDIR}/generated_aa/{{model}}/{{prompt}}.fasta",
    params:
        kws=lambda _, input: " ".join(["-d", "-f", input.generated]),
    singularity:
        ENV.singularity.get("similarity")
    output:
        temp(f"{OUTDIR}/.similarity_tmp_aa/{{model}}/{{prompt}}-self.csv"),


rule fmt_similarity:
    input:
        index=f"{INDICES}/{{model}}/{{prompt}}",
        tmp=f"{OUTDIR}/.similarity_tmp_{{molecule}}/{{model}}/{{prompt}}-{{type}}.csv",
    singularity:
        ENV.singularity.get("fmt_similarity")
    params:
        cols=",".join(
            [
                "query",
                "index",
                "length1",
                "length2",
                "score",
                "end_query",
                "end_ref",
                "n_matches",
                "similarities",
                "length",
            ]
        ),
    output:
        f"{OUTDIR}/{{molecule}}_similarity/{{model}}/{{prompt}}-{{type}}.csv",
    shell:
        """
        if [[ {wildcards.type} == 'to_prompt' ]]; then
            xan rename -n {params.cols} {input.tmp} | \
                  xan join index {input.index} - | \
                  xan transform query '"{wildcards.prompt}"' |
                  xan drop index > {output[0]}
        else
            xan rename -n {params.cols} {input.tmp} | \
                  xan join index {input.index} - | \
                  xan drop index | \
                  xan join -r right_ query - index {input.index} | \
                  xan drop right_index,query | \
                  xan rename --replace right_id query > {output[0]}
         fi
         """
