from pathlib import Path
import time
from env import SnakeEnv
import os


configfile: "env.yaml"


"""
Output is structured as

<outdir>/
├── generated/
│   └── <model_name>/
│       └── <prefix_name>.fasta
├── prefix_comparison.csv
├── perturbation_sensitivity.csv
├── motifs_domains.csv
└── physicochemical.csv
"""

ENV = SnakeEnv.new(config)
OUTDIR = ENV.outdir
DATASETS = ENV.datasets

OUTPUTS = ENV.get_outputs()


rule all:
    input:
        *OUTPUTS["generated"],
        *OUTPUTS["motifs"],
        *OUTPUTS["metrics"],


rule generate:
    output:
        f"{OUTDIR}/generated/{{model}}/{{prefix}}.fasta",
    singularity:
        lambda wc: ENV.model_image(wc.get("model"))
    shell:
        lambda wc: ENV.model_script(wc.get("model"))


rule find_motifs:
    input:
        f"{OUTDIR}/generated/{{model}}/{{prefix}}.fasta",
    output:
        tsv=f"{OUTDIR}/motifs/{{model}}/{{prefix}}.tsv",
    params:
        prefix_fasta=lambda wc: ENV.prefix2file[wc.get("prefix")],
