g: Genome Language Model {shape: cylinder}
s: Generated sequences {shape: oval}

pl: Phylogenetic placement \n\[EPA-NG\] {shape: diamond}
cls: Taxonomic classification \n\[KRAKEN, mmseqs2\] {shape: diamond}
sim: Pairwise sequence simliarity \n\[parasail aligner\] {shape: diamond}
trans: Translate to AA {shape: diamond}
msearch: Motif finding\n\[MEME suite FIMO\] {shape: diamond}

Inputs: {
  tree: Prompt-specific phylogenetic tree {shape: package}
  p: Prompt {shape: package}
  og: Prompt (full sequence) {shape: package}
  db: Taxonomy database {shape: package}
  mdb: Motif database\nPossibly prompt-specific {shape: package}
}

Inputs.p -> g -> s
s -> sim
Inputs.og -> sim
s -> pl
Inputs.tree -> pl
s -> cls
Inputs.db -> cls
Inputs.og -> msearch
s -> msearch
Inputs.mdb -> msearch
s -> trans
Inputs.og -> trans

cns: Compare results for generated sequences against one another to measure consistency\;\ncompare with full prompt to measure novelty {
  label.near: outside-bottom-center
  _.msearch -> Motif counts
  _.trans -> "Protein properties\nHydrophobicity, isoelectric point, M.W. etc."
  _.cls -> Taxonomic assignments
  _.pl -> "Evolutionary novelty measures"
  _.sim -> "Similarity scores"
}
