import sys


from pathlib import Path
from env import SnakeEnv
import os


singularity: "../../image.sif"


# TODO: you might be able to get this working if you pass it in as a script on the shell
# and no longer use the snakemake thing. Should be fine since you already can use
# the config from the SnakeEnv object


configfile: "env.yaml"


env = SnakeEnv.new(config)
os.environ["HF_HOME"] = env.huggingface
EMBEDDING_RES = env.resources["gpu40"]

config["a"] = "foo"
config["b"] = "bar"
config["c"] = "baz"


rule all:
    input:
        expand("results/from_{s}_rule.txt", s=["shell", "script", "script_cpu"]),


rule shell_rule:
    output:
        "results/from_shell_rule.txt",
    shell:
        "./shell.py -o {output}"


# TODO: [2026-04-25 Sat] you wanna check if having snakemake in the container screws up scripts
# it seems like it does, but maybe if your container doesn't have snakemake installed,
# it will work...


rule script_rule_cpu:
    output:
        "results/from_script_cpu_rule.txt",
    script:
        "script.py"


rule script_rule:
    resources:
        **EMBEDDING_RES,
    output:
        "results/from_script_rule.txt",
    script:
        "script.py"
