import sys


from pathlib import Path
from env import SnakeEnv
import os
import time


singularity: "../../image.sif"


configfile: "env.yaml"


env = SnakeEnv.new(config)
os.environ["HF_HOME"] = env.huggingface
EMBEDDING_RES = env.resources["gpu40"]

config["a"] = "foo"
config["b"] = "bar"
config["c"] = "baz"


rule all:
    input:
        "results/aggregated.txt",
        expand("results/from_{s}_rule.txt", s=["shell", "script", "script_cpu"]),
        expand("results/from_log_rule/{p}.txt", p=range(20)),


rule shell_rule:
    output:
        "results/from_shell_rule.txt",
    shell:
        "./shell.py -o {output}"


rule script_rule_cpu:
    output:
        "results/from_script_cpu_rule.txt",
    script:
        "script.py"


rule script_rule:
    resources:
        **EMBEDDING_RES,
    output:
        "results/from_script_rule.txt",
    script:
        "script.py"


logfile = time.strftime("%Y-%M-%d_%H:%M_main.log")


rule trying_to_log:
    params:
        log=logfile,
    output:
        "results/from_log_rule/{pat}.txt",
    script:
        "try_logging.py"


checkpoint make_randoms:
    output:
        "results/rand/{out}.txt",
    shell:
        "hexdump -n 16 -v -e '/1 \"%02X\"' /dev/urandom > {out}"


# You can also inject wildcards into the rule make_randoms
# Best used if the checkpoint produces a directory


def collect_randoms(wc):  # wildcards 'wc' are obtained from the CALLING rule,
    # not the checkpoint
    ckpt_out = checkpoints.make_randoms.get().output[0]
    files = glob_wildcards("results/rand/{out}.txt").out
    print(ckpt_out)
    return ckpt_out


rule aggregate_randoms:
    input:
        collect_randoms,
    output:
        "results/aggregated.txt",
    shell:
        "cat {input} > {output}"
