__definitions__:
  - import polars as pl
  - scols = pl.read_csv(input["sample_meta"], n_rows = 5).columns

datasets:
  ast:
    path: ?input["ast"]
  sample_meta:
    path: ?input["sample_meta"]
  seq_meta:
    path: ?input["seq_meta"]

views:
  "Taxonomy":
    dataset: sample_meta
    desc: "Taxonomic attributes"
    render-table:
      columns:
        ?for col in scols:
          ?if col not in params["tax_cols"] and col != "sample":
            ?col:
              display-mode: hidden
  "Annotation counts":
    desc: "Number of unique sequence annotations within each sample"
    dataset: seq_meta
  "Sample handling":
    desc: "Metadata relating to sequencing and AST platform"
    dataset: sample_meta
    render-table:
      columns:
        ?for col in scols:
          ?if col not in params["handle_cols"] and col != "sample":
            ?col:
              display-mode: hidden
  "Source":
    desc: "Information about how samples were sourced"
    dataset: sample_meta
    render-table:
      columns:
        ?for col in scols:
          ?if col not in params["source_cols"] and col != "sample":
            ?col:
              display-mode: hidden
  "Pathologic":
    desc: "Pathological details"
    dataset: sample_meta
    render-table:
      columns:
        ?for col in scols:
          ?if col not in params["patho_cols"] and col != "sample":
            ?col:
              display-mode: hidden
  "AST":
    dataset: ast
    desc: "Antibiotic Susceptibility Testing data (resistance classification and AST value)"
    render-table:
      columns:
        ?for col in params["ast_boolean"]:
          ?f"{col}":
            spell:
              url: v1.5.1/logic/boolean
              with:
                true_value: 1
                false_value: 0
        ?for col in params["ast"]:
          ?f"{col}":
            plot:
              ticks:
                scale: log
                color:
                  range: ["green", "red"]
