cores: 1
jobs: 10
executor: slurm
slurm-logdir: "/data/home/shannc/amr_predict/snakemake/slurm_logs"
default-resources:
  mem: 50G
  qos: cpu24h
rerun-triggers: mtime
keep-incomplete: True
delete-all-output: False
delete-temp-output: False
rerun-incomplete: True
