gi:
  - "feces?"
  - "faecal"
  - "stool"
  - "rect(al|um)?"
  - "perianal"
  - "anal"
  - "perirectal"
  - "mouth"
  - "teeth"
  - "gut"
  - "intestin"
  - "endotracheal"
  - "bowel"
  - "colon"
  - "anus"

resp:
  - "nasal"
  - "nose"
  - "pharynx"
  - "throat"
  - "trach"
  - "trache"
  - "bronch[io]"
  - "sput"
  - "respiratory"
  - "sinus"
  - "lung"

eye:
  - "eye"
  - "cornea"

accessory:
  - "hair"
  - "nail"

skin:
  - "skin"
  - "abdomen"
  - "lip"
  - "feet"
  - "gum_swab"
  - "mandible"
  - "shoulder_swab"
  - "cheek"
  - "muscle"
  - "pyoderma"
  - "foot"
  - "toe"
  - "leg"
  - "thigh"
  - "gr[oi][io]n"
  - "neck"
  - "sacrum"
  - "epidermal"
  - "eustachian"
  - "hip"
  - "arm"
  - "hand"
  - "ear"
  - "ankle"
  - "bullae"
  - "buttock"
  - "carpus"
  - "chalzion"
  - "chest_wall_wound"
  - "dental_abscess_swab"
  - "draining_tract_on_foot"
  - "elbow_swab"

fluid:
  - "fluid"
  - "effusion"
  - "ascit"
  - "pleural"
  - "peritone(al|um)"
  - "synovial"
  - "seroma"
  - "exudate"
  - "hematoma"
  - "aspirate"
  - "aspirate,_jp_drain"
  - "cerebrospinal_fluid"
  - "cerebrospinal_fluid_(csf)"
  - "csf"
  - "cholecystostomy_tube_bile"
  - "cholecystostomy_tube_fluid"
  - "exud"
  - "exudate"

wound:
  - "necrotic"
  - "wound"
  - "meningitis"
  - "mastitis"
  - "ulcer"
  - "lesion"
  - "abs?cess"
  - "absc"
  - "pustule"
  - "scab"
  - "crust"
  - "aortic_root_graft_abscess"
  - "aspirate_swab"
  - "bite_wound"
  - "bite_wound_tissue"
  - "coccygeal_lesions"
  - "crust_swab"
  - "diabetic_ulcer"

tissue:
  - "tissue"
  - "abdominal"
  - "breast"
  - "stomach"
  - "organ"
  - "liver"
  - "kidney"
  - "spleen"
  - "heart"
  - "blood_?"
  - "aorta"
  - "fat"
  - "brain"
  - "lymph"
  - "pancreas"
  - "thorax"
  - "thoracic"
  - "omentum"
  - "sternal"
  - "retroperitoneum"
  - "mammary"
  - "prostate"

urogen:
  - "u[ir][ri]ne"
  - "semen"
  - "bartholin"
  - "bladder"
  - "drainage"
  - "bil[ie]"
  - "urinary"
  - "ureth"
  - "penis"
  - "testicle"
  - "scrot"
  - "prepuce"
  - "uterine"
  - "vagina"
  - "labia"
  - "vulva"
  - "uter"
  - "pyometra"

surgical:
  - "surg"
  - "catheter"
  - "incision"
  - "implant"
  - "hardware"
  - "hware"
  - "tplo"
  - "tta"
  - "post_op"
  - "surgical_site"
  - "procedure"

joint:
  - "joint"
  - "trochanter"
  - "stifle"
  - "hock"
  - "vertebra"
  - "bone"
  - "orthopedic"
  - "cartilage"

animal:
  - "canis_lupus"
  - "^animal_cattle"
  - "paw"
  - "^animal_chicken"
  - "swine"
  - "dairy_cattle"
  - "drums"
  - "canine"
  - "turkey"

food_animal:
  - "eggs"
  - "milk"
  - "shrimp"
  - "turkey"
  - "hog"
  - "gallus_gallus"
  - "salmon"
  - "^boneless.*_chicken.*"
  - "gizzard"
  - "pork"
  - "chops"
  - "beef"
  - "chicken"
  - "chc?kn"
  - "cb_"
  - "tilapia"
  - "rte"
  - "ground_"
  - "_raw_intact"
  - "patties"
  - "pet_treat"

food_plant:
  - "food"
  - "avocado"
  - "coconut"
  - "produce"
  - "mango"
  - "peach"
  - "almond"
  - "raw"

env:
  - "soil"
  - "ground"
  - "environment"
  - "farm"

unknown:
  - "not_collected"
  - "unknown"
  - "other"
  - "bcb"
  - "anaerobic_culture"
  - "medical.*ward"
  - "tissu$"
  - "wings"
  - "_cut_in_lab"
  - "swab"
  - "mixed_parts"
  - "drain"
  - "human"
  - "pus"
