AM_classes: # Compounds/combinations not present in ADB. Combinations use ADB nomenclature
  ampicillin-sulbactam: "beta-lactam (penicillin) + beta-lactamase inhibitor"
  piperacillin-tazobactam: "beta-lactam (ureidopenicillin) + beta-lactamase inhibitor (penicillanic acid sulfone)"
  cefotaxime-clavulanic acid: "beta-lactam (cephalosporin, third generation) + beta-lactamase inhibitor (clavam, bicyclic beta-lactam without a penicillin or cephalosporin nucleus)"
  ceftazidime-clavulanic acid: "beta-lactam (cephalosporin) + beta-lactamase inhibitor (clavam, bicyclic beta-lactam without a penicillin or cephalosporin nucleus)"
  amphotericin b: "antifungal"
  anidulafungin: "antifungal"
  caspofungin: "antifungal"
  micafungin: "antifungal"
  fluconazole: "antifungal"
  voriconazole: "antifungal"
  isavuconazole: "antifungal"
  itraconazole: "antifungal"
  imipenem-edta-pa: "beta-lactam (carbapenem) + small molecule antibacterial agent"
  ceftazidime-avibactam: "beta-lactam (cephalosporin) + beta-lactamase inhibitor (non-beta-lactam beta-lactamase inhibitor, diazabicyclooctane [dbo])"
  ticarcillin-clavulanic acid: "beta-lactam (carboxypenicillin) + beta-lactamase inhibitor (clavam, bicyclic beta-lactam without a penicillin or cephalosporin nucleus)"
  quinupristin-dalfopristin: "streptogramin"

AM_of_interest:
  - "beta-lactam \\(cephalosporin, third generation\\)"
  - "carbapenem"
  - "fluoroquinolone"
  - "macrolide"

AM_groups:
  # ESKAPEE:
  #   - eScientificName: "Enterococcus faecium"
  #     vancomycin_class: "resistant"
  #   - ScientificName: "Staphylococcus aureus"
  #     resistant: ["Beta-lactam (penicillin)", "", ""]
  # 2024 WHO Bacterial Priority Pathogens List
  WHO_critical:
    - exact:
        order: "Enterobacterales"
      drug_class_re: "beta-lactam \\(cephalosporin, third generation\\)"
    - exact:
        order: "Enterobacterales"
      drug_class_re: "carbapenem"
    - exact:
        species: "Acinetobacter baumannii"
      drug_class_re: "carbapenem"
  WHO_high:
    - exact:
        genus: "Shigella"
      drug_class_re: "fluoroquinolone"
    - exact:
        # For this dataset, encompasses typhoidal and non-typhoidal fluoroquinolone-resistant Salmonella
        species: "Salmonella enterica"
      drug_class_re: "fluoroquinolone"
    - exact:
        species: "Enterococcus faecium"
      drug_name: "vancomycin"
    - exact:
        species: "Pseudomonas aeruginosa"
      drug_class_re: "carbapenem"
    - exact:
        species: "Neisseria gonorrhoeae"
      drug_class_re:
        ["beta-lactam \\(cephalosporin, third generation\\)", "fluoroquinolone"]
    - exact:
        species: "Staphylococcus aureus"
      drug_name: "methicillin"
  WHO_medium:
    - exact:
        species: ["Streptococcus pneumoniae", "Streptococcus pyogenes"]
      drug_class_re: "macrolide"
    - exact:
        species: "Haemophilus influenzae"
      drug_name: "ampicillin"
    - exact:
        species: "Streptococcus agalactiae"
      drug_name: "beta-lactam \\(penicillin\\)"
