# Only for genomes which aren't available from refseq already or have insufficient data for QC
paths:
  kraken2:
    [
      "/data/project/stemcell/shannc/repos/amr_predict/output/ast_browser/bacass_2025-12-05/Kraken2",
    ]
    # Output directory for bacass kraken2
  kraken2_expected_taxids: /data/home/shannc/amr_predict/data/temp/ast_subsampled_sample2taxid.tsv
  # headerless tsv file mapping sample ids to expected NCBI taxids
  # first column is sample ids, second taxids
  quast: [
      "/data/project/stemcell/shannc/repos/amr_predict/output/ast_browser/bacass_2025-12-05/QUAST/report/transposed_report.tsv",
    ] # Nextflow summary for bacass quast
  fastani:
    ["/data/home/shannc/amr_predict/data/temp/2026-01-26_fastani_result.tsv"]
    # Summary file from fastANI

run:
  # Foreign Contamination Screening: https://github.com/ncbi/fcs
  fcs: # Aside from `fasta-input`, values are the same as they are in the cli versions
    fasta-input: # TODO: get it from nextflow
    image: "~/tools/fcs-adaptor.sif"
    taxonomy: prok
    container-engine: singularity
  # Average Nucleotide Identity estimation: https://github.com/ParBLiSS/FastANI
  fastani:
    mapping:
      query2taxid: /data/home/shannc/amr_predict/data/temp/ast_subsampled_query2taxid.tsv
      # tsv file mapping query fasta files to NCBI taxids
      taxid2reference: /data/home/shannc/amr_predict/data/temp/ast_subsampled_taxid2ref.yaml
      # yaml file mapping NCBI taxids to list of reference genomes
      # Other k, v pairs are fastANI long flags
    kmer: 16
    threads: 1
    fragLen: 3000
    maxRatioDiff: 10.0

kraken2:
  min_percent_expected: # Minimum percent of reads from sample matching to their expected taxid
  max_percent_other: null # Maximum percent percent of reads from sample matching to other taxids at the same taxonomic level

# Adopted from NCBI refseq standards
quast:
  filters:
    - ["Total length", "<", 15000000] # Remove assemblies that are too big
    - ["Total length", ">", 300000] # Remove assemblies that are too small
    # Filter out fragmented assemblies
    - ["# contigs", "<", 2000]
    - ["N50", ">", 5000]
    - ["L50", "<", 500]

fastani:
  # tuples of [<operator>, value] e.g. [">", 90]
  ani_avg: null
  ani_all: [">", 90]
  ani_any: [">=", 96]
