# [2025-12-29 Mon] Currently set up for batch 1
pool_embeddings:
  methods:
    - method: mean
    - method: sum
    - method: similarity

seq_metadata:
  renaming_rules:
    id_col: "sample"
    seqid_col: "seqid"
    start_col: "start"
    stop_col: "stop"
    # Change the below to reflect the batch (or `all` when you eventually combine them)
  hamronization: "../data/remote/output/ast_browser/funcscan/batch1/reports/hamronization_summarize/hamronization_combined_report.tsv" # hamronization summary tsv
  combgc: "../data/remote/output/ast_browser/funcscan/batch1/reports/combgc" # combgc directory
  bakta: "../data/remote/output/ast_browser/funcscan/batch1/annotation/bakta/all" # bakta directory
  ampcombi: "../data/remote/output/ast_browser/funcscan/batch1/reports/ampcombi2/Ampcombi_summary_cluster.tsv" # Ampcombi summary cluster tsv

genomes: "../data/remote/genomes/ast_browser_batches/1" # Genome directory, relative to REMOTE
