paths: # Multiple entries supported for all. Will be automatically detected
  kraken2: [] # Can be directory containing per-sample reports. Reports are expected to be named <SAMPLE_NAME>.kraken2.report.txt"
  kraken2_expected_taxids: # A tsv file mapping sample names to the taxids that they should be compared to
  quast: []
  fastani: []
  fcs: []

run:
  fcs: # Aside from `fasta-input`, values are the same as they are in the cli versions
    fasta-input: # text file listing genomes, one on each line
    image:
    taxonomy:
    container-engine:
  fastani:
    mapping:
      query2reference: # tsv file mapping query files to references they should use
      query2taxid: # tsv file mapping query files to NCBI taxids
      taxid2reference: # yaml file with taxids as top-level keys and reference files as values. Each query file with the given taxid will only be compared to the corresponding references defined here
      # Other k, v pairs are fastANI long flags
    kmer: 16
    threads: 1
    fragLen: 3000
    maxRatioDiff: 10.0

kraken2:
  min_percent_expected: # Minimum percent of reads from sample matching to their expected taxid
  max_percent_other: # Maximum percent percent of reads from sample matching to other taxids at the same taxonomic level

# All values for quast can either be numeric which is interpreted as samples must have value higher
# than the config value to be accepted
#
# Or a tuple of [<operator>, value] defining allowed samples e.g.
# EX: N50 = ['>', 90] means accept samples with N50 > 90
quast:
  "# contigs (>= 0 bp)": null
  "# contigs (>= 1000 bp)": null
  "# contigs (>= 5000 bp)": null
  "# contigs (>= 10000 bp)": null
  "# contigs (>= 25000 bp)": null
  "# contigs (>= 50000 bp)": null
  "Total length (>= 0 bp)": null
  "Total length (>= 1000 bp)": null
  "Total length (>= 5000 bp)": null
  "Total length (>= 10000 bp)": null
  "Total length (>= 25000 bp)": null
  "Total length (>= 50000 bp)": null
  "# contigs": null
  "Largest contig": null
  "Total length": null
  "GC (%)": null
  "N50": null
  "N90": null
  "auN": null
  "L50": null
  "L90": null
  "# N's per 100 kbp": null

fastani:
  # tuples of [<operator>, value] e.g. [">", 90]
  ani_avg: null
  ani_all: null
  ani_any: null
