#!/bin/bash

# Created by argbash-init v2.10.0
# ARG_OPTIONAL_BOOLEAN([cpu])
# ARG_OPTIONAL_BOOLEAN([gpu])
# ARG_OPTIONAL_BOOLEAN([shell])
# ARG_OPTIONAL_SINGLE([download],[d],[Path to download file])
# ARG_OPTIONAL_SINGLE([input],[i],[Path to input file or directory])
# ARG_OPTIONAL_SINGLE([outdir],[o],[Path to output direcotry])
# ARG_HELP([<The general help message of my script>])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info

die() {
    local _ret="${2:-1}"
    test "${_PRINT_HELP:-no}" = yes && print_help >&2
    echo "$1" >&2
    exit "${_ret}"
}

begins_with_short_option() {
    local first_option all_short_options='dioh'
    first_option="${1:0:1}"
    test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_cpu="off"
_arg_gpu="off"
_arg_shell="off"
_arg_download=
_arg_input=
_arg_outdir=

print_help() {
    printf '%s\n' "<The general help message of my script>"
    printf 'Usage: %s [--(no-)cpu] [--(no-)gpu] [--(no-)shell] [-d|--download <arg>] [-i|--input <arg>] [-o|--outdir <arg>] [-h|--help]\n' "$0"
    printf '\t%s\n' "-d, --download: Path to download file (no default)"
    printf '\t%s\n' "-i, --input: Path to input file or directory (no default)"
    printf '\t%s\n' "-o, --outdir: Path to output direcotry (no default)"
    printf '\t%s\n' "-h, --help: Prints help"
}

parse_commandline() {
    while test $# -gt 0; do
        _key="$1"
        case "$_key" in
        --no-cpu | --cpu)
            _arg_cpu="on"
            test "${1:0:5}" = "--no-" && _arg_cpu="off"
            ;;
        --no-gpu | --gpu)
            _arg_gpu="on"
            test "${1:0:5}" = "--no-" && _arg_gpu="off"
            ;;
        --no-shell | --shell)
            _arg_shell="on"
            test "${1:0:5}" = "--no-" && _arg_shell="off"
            ;;
        -d | --download)
            test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
            _arg_download="$2"
            shift
            ;;
        --download=*)
            _arg_download="${_key##--download=}"
            ;;
        -d*)
            _arg_download="${_key##-d}"
            ;;
        -i | --input)
            test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
            _arg_input="$2"
            shift
            ;;
        --input=*)
            _arg_input="${_key##--input=}"
            ;;
        -i*)
            _arg_input="${_key##-i}"
            ;;
        -o | --outdir)
            test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
            _arg_outdir="$2"
            shift
            ;;
        --outdir=*)
            _arg_outdir="${_key##--outdir=}"
            ;;
        -o*)
            _arg_outdir="${_key##-o}"
            ;;
        -h | --help)
            print_help
            exit 0
            ;;
        -h*)
            print_help
            exit 0
            ;;
        *)
            _PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
            ;;
        esac
        shift
    done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

# vvv  PLACE YOUR CODE HERE  vvv
# For example:

sif="/data/project/sirasris_shared/genomic_evo2.sif"
script="/data/home/shannc/amr_predict/scripts/evo_prob_pred_Gene.py"
ckpt="/data/home/shannc/amr_predict/data/remote/cache/evo2_7b"
model_size="7b"

# QOS
gpu_qos="40"
if [[ "${gpu_qos}" == "40" ]]; then
    gpu="--qos=gpu40g --partition=gpu --gres=gpu:7g.40gb:1 --c 8 --ntasks=1 --mem=64G"
else
    gpu="--qos=gpu20gh --partition=gpu --gres=gpu:3g.20gb:1"
fi
binding="${ckpt}:/checkpoint,${_arg_input}:/pred_input,${_arg_outdir}:/pred_outdir"

pyargs="-c /checkpoint -i /pred_input -o /pred_outdir"

if [[ -n "${_arg_download}" ]]; then
    echo "Downloading with gpu qos ${gpu}"
    srun ${gpu} \
        singularity exec --nv "${sif}" evo2_convert_to_nemo2 \
        --model-path "hf://arcinstitute/savanna_evo2_${model_size}_base" \
        --model-size "${model_size}" \
        --output-dir "${_arg_download}"
elif [[ "${_arg_cpu}" == "on" ]]; then
    echo "srun with cpu"
    srun --qos=cpu24h singularity exec --nv -B "${binding}" "${sif}" \
        python "${script}" ${pyargs}
elif [[ "${_arg_gpu}" == "on" ]]; then
    echo "srun with gpu ${gpu}"
    srun ${gpu_mem} ${gpu} singularity exec --nv -B "${binding}" \
        "${sif}" python "${script}" ${pyargs}
elif [[ "${_arg_shell}" == "on" ]]; then
    singularity shell --nv -B "${binding}" "${sif}"
else
    singularity exec --nv -B "${binding}" "${sif}" \
        python "${script}" ${pyargs}
fi

# ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^

echo $LDFLAGS
echo $CPPFLAGS
# ] <-- needed because of Argbash
