#!/bin/bash

# Created by argbash-init v2.10.0
# ARG_OPTIONAL_BOOLEAN([cpu])
# ARG_OPTIONAL_BOOLEAN([gpu])
# ARG_OPTIONAL_BOOLEAN([shell])
# ARG_HELP([<The general help message of my script>])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info

die() {
    local _ret="${2:-1}"
    test "${_PRINT_HELP:-no}" = yes && print_help >&2
    echo "$1" >&2
    exit "${_ret}"
}

begins_with_short_option() {
    local first_option all_short_options='h'
    first_option="${1:0:1}"
    test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_cpu="off"
_arg_gpu="off"
_arg_shell="off"

print_help() {
    printf '%s\n' "<The general help message of my script>"
    printf 'Usage: %s [--(no-)cpu] [--(no-)gpu] [--(no-)shell] [-h|--help]\n' "$0"
    printf '\t%s\n' "-h, --help: Prints help"
}

parse_commandline() {
    while test $# -gt 0; do
        _key="$1"
        case "$_key" in
        --no-cpu | --cpu)
            _arg_cpu="on"
            test "${1:0:5}" = "--no-" && _arg_cpu="off"
            ;;
        --no-gpu | --gpu)
            _arg_gpu="on"
            test "${1:0:5}" = "--no-" && _arg_gpu="off"
            ;;
        --no-shell | --shell)
            _arg_shell="on"
            test "${1:0:5}" = "--no-" && _arg_shell="off"
            ;;
        -h | --help)
            print_help
            exit 0
            ;;
        -h*)
            print_help
            exit 0
            ;;
        *)
            _PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
            ;;
        esac
        shift
    done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

# vvv  PLACE YOUR CODE HERE  vvv
# For example:

sif="/data/project/sirasris_shared/genomic_evo2.sif"
script="/data/home/shannc/amr_predict/bin/evo_prob_pred_Gene.py"

if [[ "${_arg_cpu}" == "on" ]]; then
    echo "srun with cpu"
    srun --qos=cpu24h \
        singularity exec "${sif}" python "${script}" "${@}"
elif [[ "${_arg_gpu}" == "on" ]]; then
    echo "srun with gpu"
    srun --qos=gpu20gh \
        --partition=gpu \
        --gres=gpu:3g.20gb:1 \
        singularity exec "${sif}" python "${script}" "${@}"
elif [[ "${_arg_shell}" == "on" ]]; then
    singularity shell "${sif}"
else
    singularity exec "${sif}" python "${script}" "${@}"
fi

# ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^

# ] <-- needed because of Argbash
