import tempfile
import json

# Essential params to override
# output.dir
# output.config
# params.template

placeholder = None
report_dir = None
template = None
parsed_template = None
datavzrd_config = None


rule datavzrd:
    output:
        dir=directory(report_dir),
        config=datavzrd_config,  # Datavzrd config file generated by y2e
    input:
        placeholder,
    params:
        template=template,
    run:
        to_dump = {"input": dict(input), "params": dict(params)}
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".json", delete=False
        ) as variables:
            json.dump(to_dump, variables)
        shell(
            f"yte --template {params.template} --variable-file {variables.name} > {output.config}"
        )
        shell(f"mkdir {output.dir}")
        shell(f"datavzrd {output.config} --output {output.dir}")
