configfile: "env.yaml"


from datetime import date
import pandas as pd
from pathlib import Path
import os
import sys

os.environ["HF_HOME"] = config["huggingface"]

TODAY = date.today().isoformat()
DATE = config.get("date", "no_date")
IN_DATE = config.get("in_date", DATE)
TEST = config["test"]
PROFILE = "default"
if "--profile" in sys.argv:
    idx = sys.argv.index("--profile")
    if idx + 1 < len(sys.argv):
        PROFILE = sys.argv[idx + 1]
if (Path(PROFILE).exists() and Path(PROFILE).stem == "test") or PROFILE == "test":
    TEST = config["test"] = True
    print("INFO: Inferring test run from profile name...")

RAW = config["data"]["raw"]
PROCESSED = config["data"]["processed"] if not TEST else config["out"]["tests"]
TEMP = config["data"]["temp"]
TEST_DATA = config["data"]["tests"]
META = config["data"]["meta"]
REMOTE = config["remote"] if not config["test"] else config["out"]["tests"]
OUT = config["out"]["root"] if not config["test"] else config["out"]["tests"]
BIN = config["bin"]
SRC = config["src"]
LOGDIR = f"{OUT}/{DATE}/logs"


if TEST:
    GPU20 = {
        "qos": "gpu20gh",
        "gres": "gpu:3g.20gb:1",
        "partition": "gpu",
        "mem": "10G",
    }
    GPU40 = {}
    BIG_MEM = {}
else:
    GPU20 = {
        "mem": "30G",
        "qos": "gpu20gh",
        "gres": "gpu:3g.20gb:1",
        "partition": "gpu",
    }
    BIG_MEM = {"mem": "70G"}
    GPU40 = {
        "mem": "64G",
        "qos": "gpu40gh",
        "gres": "gpu:7g.40gb:1",
        "partition": "gpu",
    }
