from pathlib import Path
import time
from env import SnakeEnv, expand_nested
import os


singularity: "../../image.sif"


configfile: "env.yaml"


env = SnakeEnv.new(config)

OUTDIR = env.outdir
DATASETS = env.datasets

os.environ["HF_HOME"] = env.huggingface

if not env.test:
    EMBEDDING_RES = env.resources["gpu40"]
    EMBEDDING_RES["time"] = env.slurm_time_limit
else:
    EMBEDDING_RES = {}


def get_wc(wildcard: str):
    def f(wc):
        return wc.get(wildcard, "")

    return f


out_list = env.get_outputs()
time_prefix = time.strftime("%Y-%m-%d:%H:%M")
logdir = f"logs{'_test' if env.test else ''}/{time_prefix}"
Path(logdir).mkdir(parents=True, exist_ok=True)


rule all:
    input:
        *out_list,


# TODO: record this pattern of using a base rule and inheritance if it works
rule base:
    params:
        seqtype=get_wc("seqtype"),
        level=get_wc("level"),
        method=get_wc("method"),
        variation=get_wc("variation"),
        sae=get_wc("sae"),
        embedding_method=get_wc("embedding_method"),
        log=f"{logdir}/main.log",
        pooling=get_wc("pooling"),
    script:
        "main.py"


# Total number of datasets is 2 * n_seqtypes *
# (n_variations * n_types_variation) * n_embedding_methods * n_pooling


use rule base as make_seq_dataset with:
    output:
        directory(f"{DATASETS}/sequences/{{seqtype}}-{{variation}}-{{method}}"),
        # Variation: random, natural, perturbed
        # Seqtypes: aa, nuc
        # `Method` refers to perturbation or randomization method. It's '0' for natural
        # sequences


use rule base as get_embeddings with:  # NOTE: this saves them as an embedding cache
    input:
        rules.make_seq_dataset.output,
    retries: 5
    resources:
        **EMBEDDING_RES,
    params:
        log=f"{logdir}/embeddings.log",
    output:
        f"{DATASETS}/embedded_{{seqtype}}_{{level}}/{{variation}}-{{method}}/{{embedding_method}}-{{pooling}}.completed",


use rule base as write_seq_training_indices with:
    input:
        f"{DATASETS}/sequences/{{seqtype}}-natural-0",
    output:
        f"{OUTDIR}/training_indices/seqs_{{seqtype}}.pkl",


# Token training indices must depend on the embedding method because each one
# has different max lengths (affecting the number of tokens generated)
use rule base as write_token_training_indices with:
    input:
        f"{DATASETS}/embedded_{{seqtype}}_tokens/natural-0/{{embedding_method}}-0.completed",
    params:
        level="tokens",
    output:
        f"{OUTDIR}/training_indices/tokens_{{seqtype}}-{{embedding_method}}.pkl",


use rule base as label_cooccurrence with:
    input:
        env.metadata.file,
    params:
        tmp_file=f"{OUTDIR}/label_cooccur_tmp.csv",
    resources:
        mem="100g",
    output:
        f"{OUTDIR}/label_cooccurrence.csv",
        f"{OUTDIR}/cooccurrence_stats.yaml",


# rule evaluation:


# rule label_clustering:
#     input:
#         config["metadata"]["file"],
#     output:
#         f"{OUTDIR}/label_clusters_final.csv",
#         f"{OUTDIR}/label_cluster_stats.csv",
#     script:
#         "main.py"


use rule base as train_sae with:
    input:  # NOTE: Only train with natural sequences for now
        f"{DATASETS}/embedded_{{seqtype}}_{{level}}/natural-0/{{embedding_method}}-{{pooling}}.completed",
        branch(
            lambda wc: wc.get("level") == "tokens",
            f"{OUTDIR}/training_indices/tokens_{{seqtype}}-{{embedding_method}}.pkl",
            f"{OUTDIR}/training_indices/seqs_{{seqtype}}.pkl",
        ),
    retries: 5
    params:
        log=f"{logdir}/sae_training.log",
    output:
        f"{OUTDIR}/saes_{{seqtype}}_{{level}}/{{embedding_method}}-{{pooling}}-{{sae}}.pt",


def is_pretrained(wc):
    return wc.get("sae") in (env.saes["pretrained"] or [])


use rule base as get_activations with:
    input:
        embeddings=branch(
            is_pretrained,
            then=f"{DATASETS}/sequences/{{seqtype}}-natural-0",
            otherwise=f"{DATASETS}/embedded_{{seqtype}}_{{level}}/natural-0/{{embedding_method}}-{{pooling}}.completed",
        ),
        indices=branch(
            lambda wc: wc.get("level") == "tokens",
            f"{OUTDIR}/training_indices/tokens_{{seqtype}}-{{embedding_method}}.pkl",
            f"{OUTDIR}/training_indices/seqs_{{seqtype}}.pkl",
        ),
        sae=branch(
            is_pretrained,
            then=None,
            otherwise=lambda wc: OUTDIR
            / f"saes_{wc['seqtype']}_{wc['level']}"
            / f"{wc['embedding_method']}-{wc['pooling']}-{wc['sae']}.pt",
        ),
    output:
        directory(
            f"{DATASETS}/activations_{{seqtype}}_{{level}}/{{embedding_method}}-{{pooling}}-{{sae}}"
        ),


use rule base as embedding_metrics with:
    input:
        f"{DATASETS}/embedded_{{seqtype}}_{{level}}/natural-0/{{embedding_method}}-{{pooling}}.completed",
        f"{DATASETS}/sequences/{{seqtype}}-natural-0",
    params:
        analysis=get_wc("analysis"),
    wildcard_constraints:
        analysis="nn|corr",
    output:
        f"{env.outdir}/analyses/.{{analysis}}_tmp/{{seqtype}}_{{level}}/{{embedding_method}}-{{pooling}}.csv",
        f"{env.outdir}/analyses/.{{analysis}}_tmp/{{seqtype}}_{{level}}/{{embedding_method}}-{{pooling}}.pkl",


use rule base as perturbation_metrics with:
    input:
        natural=f"{DATASETS}/embedded_{{seqtype}}_{{level}}/natural-0/{{embedding_method}}-{{pooling}}.completed",
        perturbed=f"{DATASETS}/embedded_{{seqtype}}_{{level}}/perturbed-{{method}}/{{embedding_method}}-{{pooling}}.completed",
        random=f"{DATASETS}/embedded_{{seqtype}}_{{level}}/randomized-{{rand_method}}/{{embedding_method}}-{{pooling}}.completed",
        seqs=f"{DATASETS}/sequences/{{seqtype}}-natural-0",
    params:
        rand_method=get_wc("randomization_method"),
    output:  # hidden file to summarize later
        f"{env.outdir}/analyses/.perturbation_tmp/{{seqtype}}_{{level}}/{{method}}-{{rand_method}}-{{embedding_method}}-{{pooling}}.pkl",


use rule base as find_baseline with:
    input:
        natural=f"{DATASETS}/embedded_{{seqtype}}_{{level}}/natural-0/{{embedding_method}}-{{pooling}}.completed",
    output:
        f"{env.outdir}/analyses/.perturbation_baseline_tmp/{{seqtype}}_{{level}}/{{embedding_method}}-{{pooling}}.csv",


# * Summarize metric output

all_ptb = {
    f"{st.value}_seqs": {
        ptb: {
            rnd: {
                m: {p.value: [".pkl"] for p in mspec.poolings}
                for m, mspec in env.embedding_methods[st].items()
            }
            for rnd in env.sequence_variants.random.keys()
        }
        for ptb, ptb_spec in env.sequence_variants.perturbed.items()
        if ptb_spec.seqtype == st
    }
    for st in env.seqtypes
}


use rule base as collect_perturbation_metrics with:
    input:
        expand_nested(
            all_ptb,
            prefix=f"{env.outdir}/analyses/.perturbation_tmp",
            _0="/",
            _1="-",
            _2="-",
            _3="-",
            _4="",
        ),
    output:
        classifiability=env.outdir / "analyses/classifiability.csv",
        random_neighbor_score=env.outdir / "analyses/random_neighbor_score.csv",
        distance_correlation=env.outdir / "analyses/distance_correlation.csv",


all_emb_metrics = {
    f"{st.value}_seqs": {
        m: {p.value: [".csv", ".pkl"] for p in mspec.poolings}
        for m, mspec in env.embedding_methods[st].items()
    }
    for st in env.seqtypes
}
all_emb_metrics.update(
    {
        f"{st.value}_tokens": {
            f"{m}": {"0": [".csv", ".pkl"]} for m in env.embedding_methods[st]
        }
        for st in env.seqtypes
    }
)


use rule base as collect_embedding_metrics with:
    input:
        **{
            k: expand_nested(
                all_emb_metrics,
                prefix=f"{env.outdir}/analyses/.{k}_tmp",
                _0="/",
                _1="-",
                _2="",
            )
            for k in ("corr", "nn")
        },
    output:
        corr_all=env.outdir / "analyses/covariate_correlation_all.csv",
        nn_comparison=env.outdir / "analyses/nn_comparison.csv",
        nn_all=env.outdir / "analyses/nn_all.csv",


# rule sae_metrics:
# This rule should also get activation metrics
# TODO: report metrics on train set, including L0, MSE loss etc.
