from pathlib import Path
from env import SnakeEnv
import os


singularity: "../../image.sif"


configfile: "env.yaml"


env = SnakeEnv.new(config)

OUTDIR = env.outdir
DATASETS = env.datasets

os.environ["HF_HOME"] = env.huggingface

if not env.test:
    EMBEDDING_RES = env.resources["gpu40"]
    EMBEDDING_RES["time"] = env.slurm_time_limit
else:
    EMBEDDING_RES = {}


def get_wc(wildcard: str):
    def f(wc):
        return wc.get(wildcard)

    return f


rule all:
    input:
        *env.get_outputs(),


rule make_seq_dataset:
    params:
        seqtype=get_wc("seqtype"),
        method=get_wc("method"),
        variation=get_wc("variation"),
    output:
        # Variation: random, natural, perturbed
        # Seqtypes: aa, nuc
        # `Method` refers to perturbation or randomization method. It's '0' for natural
        # sequences
        directory(f"{DATASETS}/sequences/{{seqtype}}-{{variation}}-{{method}}"),
    script:
        "main.py"


rule get_embeddings:  # NOTE: this saves them as an embedding cache
    input:
        rules.make_seq_dataset.output,
    params:
        seqtype=get_wc("seqtype"),
        level=get_wc("level"),
        embedding_method=get_wc("embedding_method"),
        pooling=get_wc("pooling"),
    resources:
        **EMBEDDING_RES,
    output:
        f"{DATASETS}/embedded_{{seqtype}}_{{level}}/{{variation}}-{{method}}/{{embedding_method}}-{{pooling}}.completed",
    script:
        "main.py"


rule write_training_indices:
    input:
        f"{DATASETS}/sequences/{{seqtype}}-natural-0",
    params:
        seqtype=get_wc("seqtype"),
        level=get_wc("level"),
    output:
        f"{OUTDIR}/training_indices/{{level}}_{{seqtype}}.json",
    script:
        "main.py"


rule label_cooccurrence:
    input:
        env.metadata.file,
    params:
        tmp_file=f"{OUTDIR}/label_cooccur_tmp.csv",
    resources:
        mem="100g",
    output:
        f"{OUTDIR}/label_cooccurrence.csv",
        f"{OUTDIR}/cooccurrence_stats.yaml",
    script:
        "main.py"


# rule evaluation:


# rule label_clustering:
#     input:
#         config["metadata"]["file"],
#     output:
#         f"{OUTDIR}/label_clusters_final.csv",
#         f"{OUTDIR}/label_cluster_stats.csv",
#     script:
#         "main.py"


rule train_sae:
    input:  # NOTE: Only train with natural sequences for now
        f"{DATASETS}/embedded_{{seqtype}}_{{level}}/natural-0/{{embedding_method}}-{{pooling}}.completed",
        f"{OUTDIR}/training_indices/{{level}}_{{seqtype}}.json",
    params:
        seqtype=get_wc("seqtype"),
        sae=get_wc("sae"),
        embedding_method=get_wc("embedding_method"),
        level=get_wc("level"),
        pooling=get_wc("pooling"),
    output:
        f"{OUTDIR}/saes_{{seqtype}}_{{level}}/{{embedding_method}}-{{pooling}}-{{sae}}.pt",
    script:
        "main.py"


def is_pretrained(wc):
    return wc.get("sae") in env.saes["pretrained"]


rule get_activations:
    input:
        embeddings=branch(
            is_pretrained,
            then=f"{DATASETS}/sequences/{{seqtype}}-natural-0",
            otherwise=f"{DATASETS}/sequences/{{seqtype}}-natural-0",
        ),
        sae=branch(
            is_pretrained,
            then=None,
            otherwise=lambda wc: OUTDIR
            / f"saes_{wc['seqtype']}_{wc['level']}"
            / f"{wc['embedding_method']}-{wc['pooling']}-{wc['sae']}.pt",
        ),
    params:
        seqtype=get_wc("seqtype"),
        sae=get_wc("sae"),
        level=get_wc("level"),
        embedding_method=get_wc("embedding_method"),
        pooling=get_wc("pooling"),
    output:
        directory(
            f"{DATASETS}/activations_{{seqtype}}_{{level}}/{{embedding_method}}-{{pooling}}-{{sae}}"
        ),


# rule neighbor_metrics:
# rule sae_metrics:
# This rule should also get activation metrics
# TODO: report metrics on train set, including L0, MSE loss etc.
